// Code generated by ent, DO NOT EDIT.

package design

import (
	"pindou/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Design {
	return predicate.Design(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Design {
	return predicate.Design(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldTitle, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldHeight, v))
}

// ColorCount applies equality check predicate on the "color_count" field. It's identical to ColorCountEQ.
func ColorCount(v int) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldColorCount, v))
}

// GridData applies equality check predicate on the "grid_data" field. It's identical to GridDataEQ.
func GridData(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldGridData, v))
}

// ShareCode applies equality check predicate on the "share_code" field. It's identical to ShareCodeEQ.
func ShareCode(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldShareCode, v))
}

// IsPublic applies equality check predicate on the "is_public" field. It's identical to IsPublicEQ.
func IsPublic(v bool) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldIsPublic, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Design {
	return predicate.Design(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Design {
	return predicate.Design(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Design {
	return predicate.Design(sql.FieldContainsFold(FieldUserID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Design {
	return predicate.Design(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Design {
	return predicate.Design(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Design {
	return predicate.Design(sql.FieldContainsFold(FieldTitle, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldHeight, v))
}

// ColorCountEQ applies the EQ predicate on the "color_count" field.
func ColorCountEQ(v int) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldColorCount, v))
}

// ColorCountNEQ applies the NEQ predicate on the "color_count" field.
func ColorCountNEQ(v int) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldColorCount, v))
}

// ColorCountIn applies the In predicate on the "color_count" field.
func ColorCountIn(vs ...int) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldColorCount, vs...))
}

// ColorCountNotIn applies the NotIn predicate on the "color_count" field.
func ColorCountNotIn(vs ...int) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldColorCount, vs...))
}

// ColorCountGT applies the GT predicate on the "color_count" field.
func ColorCountGT(v int) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldColorCount, v))
}

// ColorCountGTE applies the GTE predicate on the "color_count" field.
func ColorCountGTE(v int) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldColorCount, v))
}

// ColorCountLT applies the LT predicate on the "color_count" field.
func ColorCountLT(v int) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldColorCount, v))
}

// ColorCountLTE applies the LTE predicate on the "color_count" field.
func ColorCountLTE(v int) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldColorCount, v))
}

// GridDataEQ applies the EQ predicate on the "grid_data" field.
func GridDataEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldGridData, v))
}

// GridDataNEQ applies the NEQ predicate on the "grid_data" field.
func GridDataNEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldGridData, v))
}

// GridDataIn applies the In predicate on the "grid_data" field.
func GridDataIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldGridData, vs...))
}

// GridDataNotIn applies the NotIn predicate on the "grid_data" field.
func GridDataNotIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldGridData, vs...))
}

// GridDataGT applies the GT predicate on the "grid_data" field.
func GridDataGT(v string) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldGridData, v))
}

// GridDataGTE applies the GTE predicate on the "grid_data" field.
func GridDataGTE(v string) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldGridData, v))
}

// GridDataLT applies the LT predicate on the "grid_data" field.
func GridDataLT(v string) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldGridData, v))
}

// GridDataLTE applies the LTE predicate on the "grid_data" field.
func GridDataLTE(v string) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldGridData, v))
}

// GridDataContains applies the Contains predicate on the "grid_data" field.
func GridDataContains(v string) predicate.Design {
	return predicate.Design(sql.FieldContains(FieldGridData, v))
}

// GridDataHasPrefix applies the HasPrefix predicate on the "grid_data" field.
func GridDataHasPrefix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasPrefix(FieldGridData, v))
}

// GridDataHasSuffix applies the HasSuffix predicate on the "grid_data" field.
func GridDataHasSuffix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasSuffix(FieldGridData, v))
}

// GridDataEqualFold applies the EqualFold predicate on the "grid_data" field.
func GridDataEqualFold(v string) predicate.Design {
	return predicate.Design(sql.FieldEqualFold(FieldGridData, v))
}

// GridDataContainsFold applies the ContainsFold predicate on the "grid_data" field.
func GridDataContainsFold(v string) predicate.Design {
	return predicate.Design(sql.FieldContainsFold(FieldGridData, v))
}

// ShareCodeEQ applies the EQ predicate on the "share_code" field.
func ShareCodeEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldShareCode, v))
}

// ShareCodeNEQ applies the NEQ predicate on the "share_code" field.
func ShareCodeNEQ(v string) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldShareCode, v))
}

// ShareCodeIn applies the In predicate on the "share_code" field.
func ShareCodeIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldShareCode, vs...))
}

// ShareCodeNotIn applies the NotIn predicate on the "share_code" field.
func ShareCodeNotIn(vs ...string) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldShareCode, vs...))
}

// ShareCodeGT applies the GT predicate on the "share_code" field.
func ShareCodeGT(v string) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldShareCode, v))
}

// ShareCodeGTE applies the GTE predicate on the "share_code" field.
func ShareCodeGTE(v string) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldShareCode, v))
}

// ShareCodeLT applies the LT predicate on the "share_code" field.
func ShareCodeLT(v string) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldShareCode, v))
}

// ShareCodeLTE applies the LTE predicate on the "share_code" field.
func ShareCodeLTE(v string) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldShareCode, v))
}

// ShareCodeContains applies the Contains predicate on the "share_code" field.
func ShareCodeContains(v string) predicate.Design {
	return predicate.Design(sql.FieldContains(FieldShareCode, v))
}

// ShareCodeHasPrefix applies the HasPrefix predicate on the "share_code" field.
func ShareCodeHasPrefix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasPrefix(FieldShareCode, v))
}

// ShareCodeHasSuffix applies the HasSuffix predicate on the "share_code" field.
func ShareCodeHasSuffix(v string) predicate.Design {
	return predicate.Design(sql.FieldHasSuffix(FieldShareCode, v))
}

// ShareCodeIsNil applies the IsNil predicate on the "share_code" field.
func ShareCodeIsNil() predicate.Design {
	return predicate.Design(sql.FieldIsNull(FieldShareCode))
}

// ShareCodeNotNil applies the NotNil predicate on the "share_code" field.
func ShareCodeNotNil() predicate.Design {
	return predicate.Design(sql.FieldNotNull(FieldShareCode))
}

// ShareCodeEqualFold applies the EqualFold predicate on the "share_code" field.
func ShareCodeEqualFold(v string) predicate.Design {
	return predicate.Design(sql.FieldEqualFold(FieldShareCode, v))
}

// ShareCodeContainsFold applies the ContainsFold predicate on the "share_code" field.
func ShareCodeContainsFold(v string) predicate.Design {
	return predicate.Design(sql.FieldContainsFold(FieldShareCode, v))
}

// IsPublicEQ applies the EQ predicate on the "is_public" field.
func IsPublicEQ(v bool) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldIsPublic, v))
}

// IsPublicNEQ applies the NEQ predicate on the "is_public" field.
func IsPublicNEQ(v bool) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldIsPublic, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Design {
	return predicate.Design(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Design {
	return predicate.Design(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Design {
	return predicate.Design(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Design) predicate.Design {
	return predicate.Design(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Design) predicate.Design {
	return predicate.Design(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Design) predicate.Design {
	return predicate.Design(sql.NotPredicates(p))
}
