// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DesignsColumns holds the columns for the "designs" table.
	DesignsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Default: "未命名作品"},
		{Name: "width", Type: field.TypeInt, Default: 32},
		{Name: "height", Type: field.TypeInt, Default: 32},
		{Name: "color_count", Type: field.TypeInt, Default: 48},
		{Name: "grid_data", Type: field.TypeString, Size: 2147483647},
		{Name: "share_code", Type: field.TypeString, Nullable: true},
		{Name: "is_public", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DesignsTable holds the schema information for the "designs" table.
	DesignsTable = &schema.Table{
		Name:       "designs",
		Columns:    DesignsColumns,
		PrimaryKey: []*schema.Column{DesignsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "design_user_id",
				Unique:  false,
				Columns: []*schema.Column{DesignsColumns[1]},
			},
			{
				Name:    "design_share_code",
				Unique:  true,
				Columns: []*schema.Column{DesignsColumns[7]},
			},
			{
				Name:    "design_created_at",
				Unique:  false,
				Columns: []*schema.Column{DesignsColumns[9]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "session_token", Type: field.TypeString, Nullable: true},
		{Name: "session_expires", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_session_token",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DesignsTable,
		UsersTable,
	}
)

func init() {
	DesignsTable.Annotation = &entsql.Annotation{
		Table: "designs",
	}
}
