// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pindou/ent/design"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Design is the model entity for the Design schema.
type Design struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// 所属用户ID
	UserID string `json:"user_id,omitempty"`
	// 作品标题
	Title string `json:"title,omitempty"`
	// 宽度(格子数)
	Width int `json:"width,omitempty"`
	// 高度(格子数)
	Height int `json:"height,omitempty"`
	// 颜色数量
	ColorCount int `json:"color_count,omitempty"`
	// 网格数据(JSON)
	GridData string `json:"grid_data,omitempty"`
	// 分享码
	ShareCode string `json:"share_code,omitempty"`
	// 是否公开
	IsPublic bool `json:"is_public,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Design) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case design.FieldIsPublic:
			values[i] = new(sql.NullBool)
		case design.FieldWidth, design.FieldHeight, design.FieldColorCount:
			values[i] = new(sql.NullInt64)
		case design.FieldID, design.FieldUserID, design.FieldTitle, design.FieldGridData, design.FieldShareCode:
			values[i] = new(sql.NullString)
		case design.FieldCreatedAt, design.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Design fields.
func (_m *Design) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case design.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case design.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case design.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case design.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = int(value.Int64)
			}
		case design.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case design.FieldColorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field color_count", values[i])
			} else if value.Valid {
				_m.ColorCount = int(value.Int64)
			}
		case design.FieldGridData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grid_data", values[i])
			} else if value.Valid {
				_m.GridData = value.String
			}
		case design.FieldShareCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field share_code", values[i])
			} else if value.Valid {
				_m.ShareCode = value.String
			}
		case design.FieldIsPublic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_public", values[i])
			} else if value.Valid {
				_m.IsPublic = value.Bool
			}
		case design.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case design.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Design.
// This includes values selected through modifiers, order, etc.
func (_m *Design) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Design.
// Note that you need to call Design.Unwrap() before calling this method if this Design
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Design) Update() *DesignUpdateOne {
	return NewDesignClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Design entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Design) Unwrap() *Design {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Design is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Design) String() string {
	var builder strings.Builder
	builder.WriteString("Design(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("color_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ColorCount))
	builder.WriteString(", ")
	builder.WriteString("grid_data=")
	builder.WriteString(_m.GridData)
	builder.WriteString(", ")
	builder.WriteString("share_code=")
	builder.WriteString(_m.ShareCode)
	builder.WriteString(", ")
	builder.WriteString("is_public=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublic))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Designs is a parsable slice of Design.
type Designs []*Design
