// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pindou/ent/design"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DesignCreate is the builder for creating a Design entity.
type DesignCreate struct {
	config
	mutation *DesignMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *DesignCreate) SetUserID(v string) *DesignCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DesignCreate) SetTitle(v string) *DesignCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *DesignCreate) SetNillableTitle(v *string) *DesignCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *DesignCreate) SetWidth(v int) *DesignCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *DesignCreate) SetNillableWidth(v *int) *DesignCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *DesignCreate) SetHeight(v int) *DesignCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *DesignCreate) SetNillableHeight(v *int) *DesignCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetColorCount sets the "color_count" field.
func (_c *DesignCreate) SetColorCount(v int) *DesignCreate {
	_c.mutation.SetColorCount(v)
	return _c
}

// SetNillableColorCount sets the "color_count" field if the given value is not nil.
func (_c *DesignCreate) SetNillableColorCount(v *int) *DesignCreate {
	if v != nil {
		_c.SetColorCount(*v)
	}
	return _c
}

// SetGridData sets the "grid_data" field.
func (_c *DesignCreate) SetGridData(v string) *DesignCreate {
	_c.mutation.SetGridData(v)
	return _c
}

// SetShareCode sets the "share_code" field.
func (_c *DesignCreate) SetShareCode(v string) *DesignCreate {
	_c.mutation.SetShareCode(v)
	return _c
}

// SetNillableShareCode sets the "share_code" field if the given value is not nil.
func (_c *DesignCreate) SetNillableShareCode(v *string) *DesignCreate {
	if v != nil {
		_c.SetShareCode(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *DesignCreate) SetIsPublic(v bool) *DesignCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *DesignCreate) SetNillableIsPublic(v *bool) *DesignCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesignCreate) SetCreatedAt(v time.Time) *DesignCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesignCreate) SetNillableCreatedAt(v *time.Time) *DesignCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesignCreate) SetUpdatedAt(v time.Time) *DesignCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesignCreate) SetNillableUpdatedAt(v *time.Time) *DesignCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DesignCreate) SetID(v string) *DesignCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DesignMutation object of the builder.
func (_c *DesignCreate) Mutation() *DesignMutation {
	return _c.mutation
}

// Save creates the Design in the database.
func (_c *DesignCreate) Save(ctx context.Context) (*Design, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesignCreate) SaveX(ctx context.Context) *Design {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesignCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesignCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesignCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := design.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := design.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := design.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.ColorCount(); !ok {
		v := design.DefaultColorCount
		_c.mutation.SetColorCount(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := design.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := design.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := design.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesignCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Design.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := design.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Design.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Design.title"`)}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "Design.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "Design.height"`)}
	}
	if _, ok := _c.mutation.ColorCount(); !ok {
		return &ValidationError{Name: "color_count", err: errors.New(`ent: missing required field "Design.color_count"`)}
	}
	if _, ok := _c.mutation.GridData(); !ok {
		return &ValidationError{Name: "grid_data", err: errors.New(`ent: missing required field "Design.grid_data"`)}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "Design.is_public"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Design.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Design.updated_at"`)}
	}
	return nil
}

func (_c *DesignCreate) sqlSave(ctx context.Context) (*Design, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Design.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesignCreate) createSpec() (*Design, *sqlgraph.CreateSpec) {
	var (
		_node = &Design{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(design.Table, sqlgraph.NewFieldSpec(design.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(design.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(design.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(design.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(design.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.ColorCount(); ok {
		_spec.SetField(design.FieldColorCount, field.TypeInt, value)
		_node.ColorCount = value
	}
	if value, ok := _c.mutation.GridData(); ok {
		_spec.SetField(design.FieldGridData, field.TypeString, value)
		_node.GridData = value
	}
	if value, ok := _c.mutation.ShareCode(); ok {
		_spec.SetField(design.FieldShareCode, field.TypeString, value)
		_node.ShareCode = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(design.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(design.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(design.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DesignCreateBulk is the builder for creating many Design entities in bulk.
type DesignCreateBulk struct {
	config
	err      error
	builders []*DesignCreate
}

// Save creates the Design entities in the database.
func (_c *DesignCreateBulk) Save(ctx context.Context) ([]*Design, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Design, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesignMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesignCreateBulk) SaveX(ctx context.Context) []*Design {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesignCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesignCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
