// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pindou/ent/design"
	"pindou/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DesignUpdate is the builder for updating Design entities.
type DesignUpdate struct {
	config
	hooks    []Hook
	mutation *DesignMutation
}

// Where appends a list predicates to the DesignUpdate builder.
func (_u *DesignUpdate) Where(ps ...predicate.Design) *DesignUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesignUpdate) SetUserID(v string) *DesignUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableUserID(v *string) *DesignUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DesignUpdate) SetTitle(v string) *DesignUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableTitle(v *string) *DesignUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *DesignUpdate) SetWidth(v int) *DesignUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableWidth(v *int) *DesignUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *DesignUpdate) AddWidth(v int) *DesignUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *DesignUpdate) SetHeight(v int) *DesignUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableHeight(v *int) *DesignUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *DesignUpdate) AddHeight(v int) *DesignUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetColorCount sets the "color_count" field.
func (_u *DesignUpdate) SetColorCount(v int) *DesignUpdate {
	_u.mutation.ResetColorCount()
	_u.mutation.SetColorCount(v)
	return _u
}

// SetNillableColorCount sets the "color_count" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableColorCount(v *int) *DesignUpdate {
	if v != nil {
		_u.SetColorCount(*v)
	}
	return _u
}

// AddColorCount adds value to the "color_count" field.
func (_u *DesignUpdate) AddColorCount(v int) *DesignUpdate {
	_u.mutation.AddColorCount(v)
	return _u
}

// SetGridData sets the "grid_data" field.
func (_u *DesignUpdate) SetGridData(v string) *DesignUpdate {
	_u.mutation.SetGridData(v)
	return _u
}

// SetNillableGridData sets the "grid_data" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableGridData(v *string) *DesignUpdate {
	if v != nil {
		_u.SetGridData(*v)
	}
	return _u
}

// SetShareCode sets the "share_code" field.
func (_u *DesignUpdate) SetShareCode(v string) *DesignUpdate {
	_u.mutation.SetShareCode(v)
	return _u
}

// SetNillableShareCode sets the "share_code" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableShareCode(v *string) *DesignUpdate {
	if v != nil {
		_u.SetShareCode(*v)
	}
	return _u
}

// ClearShareCode clears the value of the "share_code" field.
func (_u *DesignUpdate) ClearShareCode() *DesignUpdate {
	_u.mutation.ClearShareCode()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *DesignUpdate) SetIsPublic(v bool) *DesignUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *DesignUpdate) SetNillableIsPublic(v *bool) *DesignUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesignUpdate) SetUpdatedAt(v time.Time) *DesignUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DesignMutation object of the builder.
func (_u *DesignUpdate) Mutation() *DesignMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesignUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesignUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesignUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesignUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesignUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := design.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesignUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := design.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Design.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *DesignUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(design.Table, design.Columns, sqlgraph.NewFieldSpec(design.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(design.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(design.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(design.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(design.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(design.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(design.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ColorCount(); ok {
		_spec.SetField(design.FieldColorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedColorCount(); ok {
		_spec.AddField(design.FieldColorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GridData(); ok {
		_spec.SetField(design.FieldGridData, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShareCode(); ok {
		_spec.SetField(design.FieldShareCode, field.TypeString, value)
	}
	if _u.mutation.ShareCodeCleared() {
		_spec.ClearField(design.FieldShareCode, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(design.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(design.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{design.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesignUpdateOne is the builder for updating a single Design entity.
type DesignUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesignMutation
}

// SetUserID sets the "user_id" field.
func (_u *DesignUpdateOne) SetUserID(v string) *DesignUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableUserID(v *string) *DesignUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DesignUpdateOne) SetTitle(v string) *DesignUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableTitle(v *string) *DesignUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *DesignUpdateOne) SetWidth(v int) *DesignUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableWidth(v *int) *DesignUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *DesignUpdateOne) AddWidth(v int) *DesignUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *DesignUpdateOne) SetHeight(v int) *DesignUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableHeight(v *int) *DesignUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *DesignUpdateOne) AddHeight(v int) *DesignUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetColorCount sets the "color_count" field.
func (_u *DesignUpdateOne) SetColorCount(v int) *DesignUpdateOne {
	_u.mutation.ResetColorCount()
	_u.mutation.SetColorCount(v)
	return _u
}

// SetNillableColorCount sets the "color_count" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableColorCount(v *int) *DesignUpdateOne {
	if v != nil {
		_u.SetColorCount(*v)
	}
	return _u
}

// AddColorCount adds value to the "color_count" field.
func (_u *DesignUpdateOne) AddColorCount(v int) *DesignUpdateOne {
	_u.mutation.AddColorCount(v)
	return _u
}

// SetGridData sets the "grid_data" field.
func (_u *DesignUpdateOne) SetGridData(v string) *DesignUpdateOne {
	_u.mutation.SetGridData(v)
	return _u
}

// SetNillableGridData sets the "grid_data" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableGridData(v *string) *DesignUpdateOne {
	if v != nil {
		_u.SetGridData(*v)
	}
	return _u
}

// SetShareCode sets the "share_code" field.
func (_u *DesignUpdateOne) SetShareCode(v string) *DesignUpdateOne {
	_u.mutation.SetShareCode(v)
	return _u
}

// SetNillableShareCode sets the "share_code" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableShareCode(v *string) *DesignUpdateOne {
	if v != nil {
		_u.SetShareCode(*v)
	}
	return _u
}

// ClearShareCode clears the value of the "share_code" field.
func (_u *DesignUpdateOne) ClearShareCode() *DesignUpdateOne {
	_u.mutation.ClearShareCode()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *DesignUpdateOne) SetIsPublic(v bool) *DesignUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *DesignUpdateOne) SetNillableIsPublic(v *bool) *DesignUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesignUpdateOne) SetUpdatedAt(v time.Time) *DesignUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DesignMutation object of the builder.
func (_u *DesignUpdateOne) Mutation() *DesignMutation {
	return _u.mutation
}

// Where appends a list predicates to the DesignUpdate builder.
func (_u *DesignUpdateOne) Where(ps ...predicate.Design) *DesignUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesignUpdateOne) Select(field string, fields ...string) *DesignUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Design entity.
func (_u *DesignUpdateOne) Save(ctx context.Context) (*Design, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesignUpdateOne) SaveX(ctx context.Context) *Design {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesignUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesignUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesignUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := design.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesignUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := design.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Design.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *DesignUpdateOne) sqlSave(ctx context.Context) (_node *Design, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(design.Table, design.Columns, sqlgraph.NewFieldSpec(design.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Design.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, design.FieldID)
		for _, f := range fields {
			if !design.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != design.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(design.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(design.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(design.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(design.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(design.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(design.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ColorCount(); ok {
		_spec.SetField(design.FieldColorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedColorCount(); ok {
		_spec.AddField(design.FieldColorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GridData(); ok {
		_spec.SetField(design.FieldGridData, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShareCode(); ok {
		_spec.SetField(design.FieldShareCode, field.TypeString, value)
	}
	if _u.mutation.ShareCodeCleared() {
		_spec.ClearField(design.FieldShareCode, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(design.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(design.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Design{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{design.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
