// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pindou/ent/design"
	"pindou/ent/schema"
	"pindou/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	designFields := schema.Design{}.Fields()
	_ = designFields
	// designDescUserID is the schema descriptor for user_id field.
	designDescUserID := designFields[1].Descriptor()
	// design.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	design.UserIDValidator = designDescUserID.Validators[0].(func(string) error)
	// designDescTitle is the schema descriptor for title field.
	designDescTitle := designFields[2].Descriptor()
	// design.DefaultTitle holds the default value on creation for the title field.
	design.DefaultTitle = designDescTitle.Default.(string)
	// designDescWidth is the schema descriptor for width field.
	designDescWidth := designFields[3].Descriptor()
	// design.DefaultWidth holds the default value on creation for the width field.
	design.DefaultWidth = designDescWidth.Default.(int)
	// designDescHeight is the schema descriptor for height field.
	designDescHeight := designFields[4].Descriptor()
	// design.DefaultHeight holds the default value on creation for the height field.
	design.DefaultHeight = designDescHeight.Default.(int)
	// designDescColorCount is the schema descriptor for color_count field.
	designDescColorCount := designFields[5].Descriptor()
	// design.DefaultColorCount holds the default value on creation for the color_count field.
	design.DefaultColorCount = designDescColorCount.Default.(int)
	// designDescIsPublic is the schema descriptor for is_public field.
	designDescIsPublic := designFields[8].Descriptor()
	// design.DefaultIsPublic holds the default value on creation for the is_public field.
	design.DefaultIsPublic = designDescIsPublic.Default.(bool)
	// designDescCreatedAt is the schema descriptor for created_at field.
	designDescCreatedAt := designFields[9].Descriptor()
	// design.DefaultCreatedAt holds the default value on creation for the created_at field.
	design.DefaultCreatedAt = designDescCreatedAt.Default.(func() time.Time)
	// designDescUpdatedAt is the schema descriptor for updated_at field.
	designDescUpdatedAt := designFields[10].Descriptor()
	// design.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	design.DefaultUpdatedAt = designDescUpdatedAt.Default.(func() time.Time)
	// design.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	design.UpdateDefaultUpdatedAt = designDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.DefaultPasswordHash holds the default value on creation for the password_hash field.
	user.DefaultPasswordHash = userDescPasswordHash.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
